name : microservices-dev

services:
  # PostgreSQL para User Service
  postgres-user-dev:
    image: postgres:15-alpine
    container_name: postgres-user-dev
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.UTF-8"
  #  ports:
  #    - "5432:5432"
    volumes:
      - postgres-user-dev-data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  #  User Service
  user-service-dev:
    image: user-service-dev:1.0
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "9081:8081"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-user-dev:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      postgres-user-dev:
        condition: service_healthy
    networks:
      - microservice-network
    restart: unless-stopped

networks:
  microservice-network:
    driver: bridge
volumes:
  postgres-user-dev-data:
    driver: local